server:
  port: 8022
  servlet:
    context-path: /rabbitmq-example
spring:
  application:
    name: rabbitmq-example
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: admin
                password: admin
                publisher-confirms: true #如果对异步消息需要回调必须设置为true
                publisher-returns: true
      bindings:
        delayConstOutput:
          destination: delayedQueueTopic
          content-type: application/json
        delayConstInput:
          destination: delayedQueueTopic
          content-type: application/json
          group: ${spring.application.name}
        ackConstOutput:
          destination: ackQueueTopic
          content-type: application/json
        ackConstInput:
          destination: ackQueueTopic
          content-type: application/json
      rabbit:
        bindings:
          delayConstOutput:
            producer:
              delayed-exchange: true # 是否将目标exchange声明为一个延迟消息交换机，默认false。即消息productor发布消息到延迟exchange后，延迟n长时间后才将消息推送到指定的queue中。 -RabbitMQ需要安装/启用插件: rabbitmq-delayed-message-exchange
          delayConstInput:
            consumer:
              delayed-exchange: true
          ackConstInput:
            consumer:
              acknowledge-mode: manual